### ISSUE TITLE
Suggestion: Provide configs for old Node.js version

### ISSUE THREAD

**Issue by munierujp** [mightyiam/tsconfigs#363]
Recommended value of `lib` and `target` depends on the Node.js version.

cf. https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping

Could you provide configs for the old Node.js version to avoid compile errors?

## Example

My current `tsconfig.json` for Node 12.x

```json
{
  "extends": "tsconfigs/nodejs-executable",
  "compilerOptions": {
    "target": "ES2019",
    "lib": [
      "ES2019"
    ]
  }
}
```

If tsconfigs is providing configs for old Node.js version...:

```json
{
  "extends": "tsconfigs/nodejs-v12-executable"
}
```

Thank you.

**Comment by mightyiam** [comment]
Thank you for using tsconfigs, @munierujp.

That would be too much API surface. The scope of this package is as it is meant to be. This suggested variation is too specific to be included in this package. You do know that you can override any property, right?

**Comment by mightyiam** [comment]
How many times have you overridden this particular property in this particular way that it would motivate you to suggest this here?
